import { Product, ProductCategory } from "./types";

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Kit Complet Volume Russe",
    slug: "kit-complet-volume-russe",
    price: "89.90",
    regular_price: "109.90",
    sale_price: "89.90",
    description: "<p>Le kit ultime pour maitriser la technique du volume russe. Contient des cils en soie premium de differentes courbures (C, D, L), une colle professionnelle longue tenue, une pince a volume, un micro-brush set et un guide technique.</p>",
    short_description: "Kit pro volume russe avec cils, colle et accessoires",
    images: [
      { id: 1, src: "/images/products/kit-volume.jpg", alt: "Kit Complet Volume Russe" },
      { id: 2, src: "/images/products/cils-glamour.jpg", alt: "Kit Volume Russe contenu" },
    ],
    attributes: [
      { id: 1, name: "Courbure", options: ["C", "D", "L"] },
    ],
    variations: [101, 102, 103],
    variantNodes: [],
    categories: [{ id: 1, name: "Kits", slug: "kits" }],
    stock_status: "instock",
  },
  {
    id: 2,
    name: "Cils Soie Premium - Look Naturel",
    slug: "cils-soie-premium-naturel",
    price: "14.90",
    regular_price: "14.90",
    sale_price: "",
    description: "<p>Cils en soie haut de gamme pour un look naturel et subtil. Ultra-legers, souples et confortables. Duree de vie prolongee grace a notre fibre exclusive. Disponibles en plusieurs epaisseurs et longueurs.</p>",
    short_description: "Cils en soie ultra-legers pour un regard naturel",
    images: [
      { id: 3, src: "/images/products/cils-naturel.jpg", alt: "Cils Soie Look Naturel" },
    ],
    attributes: [
      { id: 1, name: "Epaisseur", options: ["0.05mm", "0.07mm", "0.10mm"] },
      { id: 2, name: "Longueur", options: ["8mm", "10mm", "12mm", "14mm"] },
    ],
    variations: [201, 202, 203, 204, 205, 206],
    variantNodes: [],
    categories: [{ id: 2, name: "Look Naturel", slug: "look-naturel" }],
    stock_status: "instock",
  },
  {
    id: 3,
    name: "Cils Volume 3D - Look Glamour",
    slug: "cils-volume-3d-glamour",
    price: "18.90",
    regular_price: "18.90",
    sale_price: "",
    description: "<p>Extensions de cils pre-faites en eventail 3D pour un look glamour intense. Gain de temps garanti : pose rapide sans sacrifier le volume. Fibre synthetique premium, noir intense.</p>",
    short_description: "Extensions pre-faites 3D pour un volume intense",
    images: [
      { id: 4, src: "/images/products/cils-glamour.jpg", alt: "Cils Volume 3D Glamour" },
    ],
    attributes: [
      { id: 1, name: "Courbure", options: ["C", "D", "DD"] },
      { id: 2, name: "Longueur", options: ["10mm", "12mm", "14mm", "16mm"] },
    ],
    variations: [301, 302, 303, 304, 305, 306],
    variantNodes: [],
    categories: [{ id: 3, name: "Look Glamour", slug: "look-glamour" }],
    stock_status: "instock",
  },
  {
    id: 4,
    name: "Colle Pro Longue Tenue",
    slug: "colle-pro-longue-tenue",
    price: "24.90",
    regular_price: "24.90",
    sale_price: "",
    description: "<p>Colle professionnelle a sechage rapide (1-2 secondes). Tenue jusqu'a 6 semaines. Formulee pour minimiser les irritations. Fonctionne dans toutes les conditions d'humidite.</p>",
    short_description: "Colle pro sechage rapide, tenue 6 semaines",
    images: [
      { id: 5, src: "/images/products/colle-pro.jpg", alt: "Colle Pro Longue Tenue" },
    ],
    attributes: [
      { id: 1, name: "Volume", options: ["5ml", "10ml"] },
    ],
    variations: [401, 402],
    variantNodes: [],
    categories: [{ id: 4, name: "Colles & Accessoires", slug: "colles-accessoires" }],
    stock_status: "instock",
  },
  {
    id: 5,
    name: "Pince Volume Ergonomique",
    slug: "pince-volume-ergonomique",
    price: "19.90",
    regular_price: "19.90",
    sale_price: "",
    description: "<p>Pince en acier inoxydable japonais de precision, specialement concue pour la creation d'eventails de volume. Grip anti-fatigue pour les longues sessions. Pointe ultra-fine et parfaitement alignee.</p>",
    short_description: "Pince acier japonais pour technique volume",
    images: [
      { id: 6, src: "/images/products/pince-volume.jpg", alt: "Pince Volume Ergonomique" },
    ],
    attributes: [],
    variations: [],
    variantNodes: [],
    categories: [{ id: 4, name: "Colles & Accessoires", slug: "colles-accessoires" }],
    stock_status: "instock",
  },
  {
    id: 6,
    name: "Cils Mega Volume - Optimal",
    slug: "cils-mega-volume-optimal",
    price: "22.90",
    regular_price: "22.90",
    sale_price: "",
    description: "<p>Notre gamme Optimal pour les techniciennes qui veulent le meilleur. Cils ultra-fins 0.03mm permettant des bouquets de 10 a 16 brins. Noir profond, courbure parfaite, memoire de forme exceptionnelle.</p>",
    short_description: "Cils ultra-fins 0.03mm pour mega volume spectaculaire",
    images: [
      { id: 7, src: "/images/products/cils-optimal.jpg", alt: "Cils Mega Volume Optimal" },
    ],
    attributes: [
      { id: 1, name: "Courbure", options: ["C", "D", "L", "M"] },
      { id: 2, name: "Longueur", options: ["8mm", "10mm", "12mm", "14mm", "16mm"] },
    ],
    variations: [601, 602, 603, 604],
    variantNodes: [],
    categories: [{ id: 5, name: "Optimal", slug: "optimal" }],
    stock_status: "instock",
  },
];

export const mockCategories: ProductCategory[] = [
  { id: 1, name: "Kits", slug: "kits", count: 1 },
  { id: 2, name: "Look Naturel", slug: "look-naturel", count: 1 },
  { id: 3, name: "Look Glamour", slug: "look-glamour", count: 1 },
  { id: 4, name: "Colles & Accessoires", slug: "colles-accessoires", count: 2 },
  { id: 5, name: "Optimal", slug: "optimal", count: 1 },
];
